"""add role and career to user

Revision ID: 88abaf8c5647
Revises: 
Create Date: 2026-01-13 22:33:27.476188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88abaf8c5647'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('career', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('career')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
